### ISSUE TITLE
Error on avatar upload in default s3 region

### ISSUE THREAD

**Issue by sheldonkotyk** [AshMenhennett/Forum#12]
AWS HTTP error: cURL error 6: Could not resolve host: s3..amazonaws.com

The extra . is the problem here. Creating a new bucket in the Oregon region works.

**Comment by sheldonkotyk** [comment]
OK, very weird. I just swapped everything back and it is working now.

**Comment by AshMenhennett** [comment]
Thank you for pointing that out.
